name: linting using cppcheck

on: [push]
jobs:
  linting:
    strategy:
    fail-fast: false
    matrix:
      sketch: ['luddite', '5x5x5']

    name: cppcheck keyboard examples
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name:  Install Cppcheck
      run: sudo apt-get install -y cppcheck
    - name:  Run Cppcheck
      run: |
        cppcheck $GITHUB_WORKSPACE/examples/keyboards/${{ matrix.sketch }}/*.ino --enable=all  --force --template=gcc --inline-suppr  --output-file=${{ matrix.sketch }}.txt 
        cat ${{ matrix.sketch }}.txt
    - name: Publish Report
      uses: actions/upload-artifact@v3
      with:
          name: cppcheck ${{ matrix.sketch }}
          path: ${{ matrix.sketch }}.txt


